In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
import pickle

In [5]:
df=pd.read_csv("dataset.csv")
df.shape

(4240, 16)

In [6]:
df.head()

   male  age  education  currentSmoker  ...    BMI  heartRate  glucose  TenYearCHD
0     1   39        4.0              0  ...  26.97       80.0     77.0           0
1     0   46        2.0              0  ...  28.73       95.0     76.0           0
2     1   48        1.0              1  ...  25.34       75.0     70.0           0
3     0   61        3.0              1  ...  28.58       65.0    103.0           1
4     0   46        3.0              1  ...  23.10       85.0     85.0           0

[5 rows x 16 columns]

In [7]:
df=df.drop(["education"],axis=1)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4240 non-null   int64
 1   age              4240 non-null   int64
 2   currentSmoker    4240 non-null   int64
 3   cigsPerDay       4211 non-null   float64
 4   BPMeds           4187 non-null   float64
 5   prevalentStroke  4240 non-null   int64
 6   prevalentHyp     4240 non-null   int64
 7   diabetes         4240 non-null   int64
 8   totChol          4190 non-null   float64
 9   sysBP            4240 non-null   float64
 10  diaBP            4240 non-null   float64
 11  BMI              4221 non-null   float64
 12  heartRate        4239 non-null   float64
 13  glucose          3852 non-null   float64
 14  TenYearCHD       4240 non-null   int64
dtypes: float64(8), int64(7)
memory usage: 497.0 KB

In [9]:
df.isnull().sum()

male                 0
age                  0
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [10]:
df['BPMeds'].value_counts()

BPMeds
0.0    4063
1.0     124
Name: count, dtype: int64

In [11]:
df['BPMeds'].fillna(1,inplace=True)

/tmp/ipython-input-613752269.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BPMeds'].fillna(1,inplace=True)

In [12]:
coll_null=['cigsPerDay','totChol','BMI','glucose','heartRate']

In [13]:
for cols in coll_null:
    df[cols].fillna(df[cols].median(),inplace=True)

/tmp/ipython-input-3807082568.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[cols].fillna(df[cols].median(),inplace=True)

In [14]:
df.isnull().sum()

male               0
age                0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [15]:
from imblearn.over_sampling import SMOTE
sm=SMOTE(random_state=42)
X,y=sm.fit_resample(df.drop(["diabetes"],axis=1),df["diabetes"])

In [129]:
# X=df.drop(["diabetes"],axis=1)
# y=df["diabetes"]

In [17]:
X.shape

(8262, 14)

In [18]:
stdscalar=StandardScaler()
X_scaled=stdscalar.fit_transform(X)
X=pd.DataFrame(X_scaled,columns=X.columns)

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
model=RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [25]:
model.score(X_test,y_test)

0.9879007864488808

In [27]:
import joblib
model=joblib.dump(model,'model.pkl')

In [26]:
from sklearn.metrics import classification_report
y_pred=model.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       819
           1       0.98      0.99      0.99       834

    accuracy                           0.99      1653
   macro avg       0.99      0.99      0.99      1653
weighted avg       0.99      0.99      0.99      1653

In [28]:
X_test.head()

          male       age  currentSmoker  ...  heartRate   glucose  TenYearCHD
2132 -0.701530  0.895583       1.447598  ...  -1.003835 -0.526619   -0.424203
8189 -0.701530  0.769579      -0.690799  ...   1.009353  1.184054    2.357359
4205 -0.701530 -0.742463      -0.690799  ...  -0.195455 -0.680991   -0.424203
789   1.425457  1.399596      -0.690799  ...  -0.824195 -0.779227   -0.424203
8131 -0.701530  1.021586      -0.690799  ...  -0.236852 -0.617603   -0.424203

[5 rows x 14 columns]